apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - patches/allowlist.yaml
  - patches/cronjobs-env.yaml
  - patches/cronjobs-schedule.yaml
  - patches/deployments-env.yaml
  - patches/deployments-resources.yaml
  - patches/hpa-min.yaml
images:
  - name: ghcr.io/altinn/dialogporten-webapi
    newTag: v.1.100.1
  - name: ghcr.io/altinn/dialogporten-graphql
    newTag: v.1.100.1
  - name: ghcr.io/altinn/dialogporten-service
    newTag: v.1.100.1
  - name: ghcr.io/altinn/dialogporten-migration-bundle
    newTag: v.1.100.1
  - name: ghcr.io/altinn/dialogporten-janitor
    newTag: v.1.100.1
