apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: graphql
  labels:
    app.kubernetes.io/name: graphql
    app.kubernetes.io/part-of: dialogporten
spec:
  entryPoints:
    - http
    - https
  routes:
    - kind: Rule
      match: Host(`placeholder.invalid`)
      middlewares:
        - name: graphql-ip-allowlist
      services:
        - name: graphql
          port: 80
