apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - patches/allowlist.yaml
  - patches/cronjobs-env.yaml
  - patches/cronjobs-schedule.yaml
  - patches/deployments-env.yaml
  - patches/deployments-resources.yaml
