apiVersion: v1
kind: ConfigMap
metadata:
  name: dialogporten-runtime
  labels:
    app.kubernetes.io/part-of: dialogporten
data:
  AZURE_APPCONFIG_URI: set-by-env
  Infrastructure__MassTransit__Host: set-by-env
