apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-so
spec:
  template:
    spec:
      containers:
        - name: web-api-so
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: staging
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-eu
spec:
  template:
    spec:
      containers:
        - name: web-api-eu
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: staging
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
spec:
  template:
    spec:
      containers:
        - name: graphql
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: staging
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  template:
    spec:
      containers:
        - name: service
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: staging
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1"
